schemaVersion: 2.3.0
metadata:
  name: aib-rhadp-example
  tags:
    - automotive
    - rhivos
    - jumpstarter
components:
  - name: runtime
    attributes:
      controller.devfile.io/vscode-extensions:
        - ms-vscode.cpptools
        - ms-vscode.cmake-tools
        - twxs.cmake
    container:
      image: quay.io/mickume/codespaces:latest
      memoryLimit: "4Gi"
      memoryRequest: "1Gi"
      cpuLimit: "4"
      cpuRequest: "1"
      mountSources: true
      # environment variables
      env:
        - name: JUMPSTARTER_GRPC_ENDPOINT
          value: "grpc.rhadp-jumpstarter.apps.CLUSTER_BASE_DOMAIN"
commands:
  - id: init-workspace
    exec:
      component: runtime
      commandLine: |
        /home/tooling/.scripts/init-workspace
events:
  postStart:
    - init-workspace
