# This is a simpler example showing
# - how to add custom rpms and containers
# - how to set the root password

name: radioapp

image:
  selinux_mode: permissive

content:
  repos:
    - id: epel
      baseurl: https://dl.fedoraproject.org/pub/epel/9/Everything/$arch/

  rpms:
    - cloud-init
    - podman
    - containernetworking-plugins
    - vsomeip3-routingmanager
    - dlt-daemon
    - openssh-server
    - openssh-clients
    - vim

  container_images:
    - source: quay.io/rhadp-examples/radio-app
      tag: "latest"
      name: localhost/app

  add_files:
    - path: /etc/containers/systemd/radio.container
      source_path: "{{WORKSPACE}}/src/radio.container"
    - path: /usr/local/bin/radio-client
      source_path: "{{WORKSPACE}}/src/radio-client-wrapper"

  chmod_files:
    - path: /usr/local/bin/radio-client
      mode: "0555"

  systemd:
    enabled_services:
      # Enable ssh daemon
      - sshd.service
      # Enable the dlt daemon
      - dlt

auth:
  # "password"
  root_password: "{{ROOT_PASSWORD}}"
