---
create_resource_group: false

vm_size: "Standard_D4ps_v5"  # ARM-based Azure VM, 4 vCPU, 16 GiB RAM
boot_disk_size: 64
additional_disk_size: 100

# Network configuration
vnet_name: "vnet-rhel-arm-{{ azure_guid }}"
vnet_cidr: "10.0.0.0/16"
subnet_name: "subnet-rhel-arm-{{ azure_guid }}"
subnet_cidr: "10.0.1.0/24"

# Security group configuration
nsg_name: "nsg-rhel-arm-{{ azure_guid }}"

# Image configuration for RHEL 10 ARM64
vm_image:
  publisher: "RedHat"
  offer: "rhel-arm64"
  sku: "10_0-arm64"
  version: "latest"
