---
# defaults for Azure VM creation
# Note: Many variables are inherited from inventory/main.yml including:
# - azure_guid, azure_resourcegroup, ansible_user, remote_ssh_public_key_file
# - azure_client_id, azure_password, azure_tenant, azure_subscription

vm_size: "Standard_D4ps_v5"  # ARM-based Azure VM, 4 vCPU, 16 GiB RAM
boot_disk_size: 64
additional_disk_size: 100
volume_mount_point: "/mnt/data"

# Azure location
azure_location: "East US 2"  # Supports ARM64 VMs

# Resource group configuration
resource_group_name: "{{ azure_resourcegroup }}"

# Network configuration
vnet_name: "vnet-rhel-arm-{{ azure_guid }}"
vnet_cidr: "10.0.0.0/16"
subnet_name: "subnet-rhel-arm-{{ azure_guid }}"
subnet_cidr: "10.0.1.0/24"

# Security group configuration
nsg_name: "nsg-rhel-arm-{{ azure_guid }}"

# VM configuration
vm_name: "vm-rhel-arm-{{ azure_guid }}"
vm_admin_username: "{{ ansible_user }}"

# Image configuration for RHEL 10 ARM64
vm_image:
  publisher: "RedHat"
  offer: "rhel-arm64"
  sku: "10_0-arm64"
  version: "latest"

# SSH key configuration
ssh_key_name: "ssh-key-rhel-arm"
