---
- name: create directories
  become: true
  ansible.builtin.file:
    path: "{{ work_dir }}/{{ github_runner_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  delegate_to: "{{ instance_public_ip }}"

- name: download the github runner
  shell: |
    cd {{ work_dir }}/{{ github_runner_dir }}

    curl -o actions-runner-linux-arm64-{{ github_runner_version }}.tar.gz \
      -L https://github.com/actions/runner/releases/download/v{{ github_runner_version }}/actions-runner-linux-arm64-{{ github_runner_version }}.tar.gz

    tar xzf ./actions-runner-linux-arm64-{{ github_runner_version }}.tar.gz
  delegate_to: "{{ instance_public_ip }}"

- name: change file permissions
  become: true
  shell: |
    cd {{ work_dir }}/{{ github_runner_dir }}

    chmod -R "0755" *
  delegate_to: "{{ instance_public_ip }}"

- name: configure the github runner
  shell: |
    cd {{ work_dir }}/{{ github_runner_dir }}

    RESPONSE=$(curl -s -L \
      -X POST \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer {{ github_pat }}" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      https://api.github.com/orgs/{{ github_org }}/actions/runners/registration-token)

    TOKEN=$(echo "$RESPONSE" | jq -r '.token')

    ./config.sh --unattended \
      --url https://github.com/{{ github_org }} \
      --token $TOKEN \
      --name "{{ github_runner_name }}" \
      --runnergroup "{{ github_runner_group }}" \
      --labels "{{ github_runner_labels }}" \
      --replace
  delegate_to: "{{ instance_public_ip }}"

- name: register the github runner as a service
  become: true
  shell: |
    cd {{ work_dir }}/{{ github_runner_dir }}

    # fix selinux issues
    # see https://github.com/actions/runner/issues/3186
    chcon system_u:object_r:usr_t:s0 ./svc.sh

    ./svc.sh install
  delegate_to: "{{ instance_public_ip }}"

- name: start the github runner
  become: true
  shell: |
    cd {{ work_dir }}/{{ github_runner_dir }}

    # fix selinux issues
    # see https://github.com/actions/runner/issues/3186
    chcon system_u:object_r:usr_t:s0 ./runsvc.sh

    ./svc.sh start
  delegate_to: "{{ instance_public_ip }}"