# Implement your install deployment tasks here
# -------------------------------------------------

- name: remove directories
  delegate_to: "{{ instance_public_ip }}"
  become: true
  ansible.builtin.file:
    path: "{{ work_dir }}/{{ item }}"
    state: absent
  with_items:
    - "{{ aib_work_dir }}"
    - "{{ github_runner_dir }}"
    - "{{ workspace_dir }}"
    
- name: create directories for the aib runner
  delegate_to: "{{ instance_public_ip }}"
  become: true
  ansible.builtin.file:
    path: "{{ work_dir }}/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  with_items:
    - "{{ aib_work_dir }}"
    - "{{ aib_work_dir }}/builds" # FIXME: remove this directory
    - "{{ aib_work_dir }}/.mpp-cache" # FIXME: remove this directory
    - "{{ workspace_dir }}"
    - "{{ images_dir }}"

- name: clone the automotive-image-builder repo
  delegate_to: "{{ instance_public_ip }}"
  become: true
  git:
    repo: "{{ aib_repo }}"
    dest: "{{ work_dir }}/{{ aib_work_dir }}/{{ aib_dest }}"
    version: "{{ aib_branch }}"
    single_branch: true
    force: true
    depth: 1

# install the github runner
- name: install github runner
  import_tasks: install_github_runner.yml