# Implement your post-install deployment tasks here
# -------------------------------------------------

- name: create other directories
  delegate_to: "{{ instance_public_ip }}"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  with_items:
    - ".docker"

- name: install additional python modules
  delegate_to: "{{ instance_public_ip }}"
  become: true
  shell: |
    pip install boto3

