# Implement your pre-install deployment tasks here
# -------------------------------------------------

- name: update and upgrade all packages
  delegate_to: "{{ instance_public_ip }}"
  become: true
  dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: install packages
  delegate_to: "{{ instance_public_ip }}"
  become: true
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "@virtualization-hypervisor"
      - "@virtualization-client"
      - "@virtualization-platform"
      - "@virtualization-tools"
      - qemu-kvm
      - libvirt
      - virt-install
      - virt-viewer

- name: install builder packages
  delegate_to: "{{ instance_public_ip }}"
  become: true
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - podman
      - podman-docker
      - git
      - python3.12
      - python3-pip
      - buildah
      - skopeo
      - jq
      - curl
      - dotnet-sdk-9.0
      - make
      - cmake
      - gcc
      - g++

  