- name: create the vm and install the software
  hosts: localhost
  vars:
    # set the following to control the install/uninstall process
    silent: false
    become_override: false
    ACTION: "UNINSTALL" # INSTALL, UNINSTALL, UPDATE

  tasks:
    - name: remove the github runner
      include_role:
        name: roles/prepare_vm
        
    - name: delete the vm (AWS)
      include_role:
        name: roles/create_vm_aws
      when: cloud_provider == "aws"

    - name: delete the vm (Azure)
      include_role:
        name: roles/create_vm_azure
      when: cloud_provider == "azure"

    