FROM centos:stream9-development AS installroot

RUN dnf update -y

# Enable copr
RUN dnf install -y 'dnf-command(copr)'
RUN dnf copr -y enable alexl/cs9-sample-images

RUN dnf install --installroot /installroot  -y --nogpgcheck vsomeip3 bash \
    boost-system boost-thread boost-log boost-chrono boost-date-time boost-atomic \
    boost-log boost-filesystem boost-regex auto-apps

FROM scratch
COPY --from=installroot /installroot ./
