name: build the application

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: [self-hosted, Linux, ARM64]
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: build the application
        run: |
          echo "building the application..."
          cd src
          cmake .
          make


